version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    entrypoint: ".docker/entrypoint.sh"
    container_name: freterapido_app
    environment:
      - DATABASE_URL=postgresql://postgres:docker@db:5432/frdb?schema=public
    restart: always
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: freterapido_db
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=dockerdb
    restart: always
